export interface City {
  slug: string;
  name: string;
  state: string;
  latitude: number;
  longitude: number;
  timezone: string;
}

export const CITIES: City[] = [
  // Capitais
  { slug: "sao-paulo", name: "São Paulo", state: "SP", latitude: -23.5505, longitude: -46.6333, timezone: "America/Sao_Paulo" },
  { slug: "rio-de-janeiro", name: "Rio de Janeiro", state: "RJ", latitude: -22.9068, longitude: -43.1729, timezone: "America/Sao_Paulo" },
  { slug: "brasilia", name: "Brasília", state: "DF", latitude: -15.7975, longitude: -47.8919, timezone: "America/Sao_Paulo" },
  { slug: "salvador", name: "Salvador", state: "BA", latitude: -12.9714, longitude: -38.5124, timezone: "America/Bahia" },
  { slug: "fortaleza", name: "Fortaleza", state: "CE", latitude: -3.7172, longitude: -38.5433, timezone: "America/Fortaleza" },
  { slug: "belo-horizonte", name: "Belo Horizonte", state: "MG", latitude: -19.9167, longitude: -43.9345, timezone: "America/Sao_Paulo" },
  { slug: "manaus", name: "Manaus", state: "AM", latitude: -3.1190, longitude: -60.0217, timezone: "America/Manaus" },
  { slug: "curitiba", name: "Curitiba", state: "PR", latitude: -25.4284, longitude: -49.2733, timezone: "America/Sao_Paulo" },
  { slug: "recife", name: "Recife", state: "PE", latitude: -8.0476, longitude: -34.8770, timezone: "America/Recife" },
  { slug: "goiania", name: "Goiânia", state: "GO", latitude: -16.6869, longitude: -49.2648, timezone: "America/Sao_Paulo" },
  { slug: "belem", name: "Belém", state: "PA", latitude: -1.4558, longitude: -48.5024, timezone: "America/Belem" },
  { slug: "porto-alegre", name: "Porto Alegre", state: "RS", latitude: -30.0346, longitude: -51.2177, timezone: "America/Sao_Paulo" },
  { slug: "guarulhos", name: "Guarulhos", state: "SP", latitude: -23.4538, longitude: -46.5333, timezone: "America/Sao_Paulo" },
  { slug: "campinas", name: "Campinas", state: "SP", latitude: -22.9099, longitude: -47.0626, timezone: "America/Sao_Paulo" },
  { slug: "sao-luis", name: "São Luís", state: "MA", latitude: -2.5297, longitude: -44.2825, timezone: "America/Fortaleza" },
  { slug: "sao-goncalo", name: "São Gonçalo", state: "RJ", latitude: -22.8269, longitude: -43.0634, timezone: "America/Sao_Paulo" },
  { slug: "maceio", name: "Maceió", state: "AL", latitude: -9.6658, longitude: -35.7353, timezone: "America/Maceio" },
  { slug: "duque-de-caxias", name: "Duque de Caxias", state: "RJ", latitude: -22.7856, longitude: -43.3117, timezone: "America/Sao_Paulo" },
  { slug: "natal", name: "Natal", state: "RN", latitude: -5.7945, longitude: -35.2110, timezone: "America/Fortaleza" },
  { slug: "teresina", name: "Teresina", state: "PI", latitude: -5.0892, longitude: -42.8019, timezone: "America/Fortaleza" },
  { slug: "campo-grande", name: "Campo Grande", state: "MS", latitude: -20.4697, longitude: -54.6201, timezone: "America/Campo_Grande" },
  { slug: "sao-bernardo-do-campo", name: "São Bernardo do Campo", state: "SP", latitude: -23.6914, longitude: -46.5646, timezone: "America/Sao_Paulo" },
  { slug: "joao-pessoa", name: "João Pessoa", state: "PB", latitude: -7.1195, longitude: -34.8450, timezone: "America/Fortaleza" },
  { slug: "santo-andre", name: "Santo André", state: "SP", latitude: -23.6737, longitude: -46.5432, timezone: "America/Sao_Paulo" },
  { slug: "osasco", name: "Osasco", state: "SP", latitude: -23.5325, longitude: -46.7917, timezone: "America/Sao_Paulo" },
  { slug: "jaboatao-dos-guararapes", name: "Jaboatão dos Guararapes", state: "PE", latitude: -8.1130, longitude: -35.0158, timezone: "America/Recife" },
  { slug: "ribeirao-preto", name: "Ribeirão Preto", state: "SP", latitude: -21.1704, longitude: -47.8103, timezone: "America/Sao_Paulo" },
  { slug: "uberlandia", name: "Uberlândia", state: "MG", latitude: -18.9186, longitude: -48.2772, timezone: "America/Sao_Paulo" },
  { slug: "sorocaba", name: "Sorocaba", state: "SP", latitude: -23.5015, longitude: -47.4526, timezone: "America/Sao_Paulo" },
  { slug: "contagem", name: "Contagem", state: "MG", latitude: -19.9320, longitude: -44.0539, timezone: "America/Sao_Paulo" },
  { slug: "aracaju", name: "Aracaju", state: "SE", latitude: -10.9091, longitude: -37.0677, timezone: "America/Maceio" },
  { slug: "feira-de-santana", name: "Feira de Santana", state: "BA", latitude: -12.2669, longitude: -38.9666, timezone: "America/Bahia" },
  { slug: "cuiaba", name: "Cuiabá", state: "MT", latitude: -15.6014, longitude: -56.0979, timezone: "America/Cuiaba" },
  { slug: "joinville", name: "Joinville", state: "SC", latitude: -26.3045, longitude: -48.8487, timezone: "America/Sao_Paulo" },
  { slug: "juiz-de-fora", name: "Juiz de Fora", state: "MG", latitude: -21.7642, longitude: -43.3503, timezone: "America/Sao_Paulo" },
  { slug: "londrina", name: "Londrina", state: "PR", latitude: -23.3045, longitude: -51.1696, timezone: "America/Sao_Paulo" },
  { slug: "niteroi", name: "Niterói", state: "RJ", latitude: -22.8833, longitude: -43.1036, timezone: "America/Sao_Paulo" },
  { slug: "ananindeua", name: "Ananindeua", state: "PA", latitude: -1.3659, longitude: -48.3886, timezone: "America/Belem" },
  { slug: "porto-velho", name: "Porto Velho", state: "RO", latitude: -8.7612, longitude: -63.9004, timezone: "America/Porto_Velho" },
  { slug: "serra", name: "Serra", state: "ES", latitude: -20.1209, longitude: -40.3075, timezone: "America/Sao_Paulo" },
  { slug: "santos", name: "Santos", state: "SP", latitude: -23.9608, longitude: -46.3336, timezone: "America/Sao_Paulo" },
  { slug: "florianopolis", name: "Florianópolis", state: "SC", latitude: -27.5954, longitude: -48.5480, timezone: "America/Sao_Paulo" },
  { slug: "vitoria", name: "Vitória", state: "ES", latitude: -20.3155, longitude: -40.3128, timezone: "America/Sao_Paulo" },
  { slug: "vila-velha", name: "Vila Velha", state: "ES", latitude: -20.3297, longitude: -40.2925, timezone: "America/Sao_Paulo" },
  { slug: "aparecida-de-goiania", name: "Aparecida de Goiânia", state: "GO", latitude: -16.8198, longitude: -49.2469, timezone: "America/Sao_Paulo" },
  { slug: "macapa", name: "Macapá", state: "AP", latitude: 0.0349, longitude: -51.0694, timezone: "America/Belem" },
  { slug: "sao-jose-dos-campos", name: "São José dos Campos", state: "SP", latitude: -23.1896, longitude: -45.8841, timezone: "America/Sao_Paulo" },
  { slug: "caxias-do-sul", name: "Caxias do Sul", state: "RS", latitude: -29.1681, longitude: -51.1794, timezone: "America/Sao_Paulo" },
  { slug: "maringa", name: "Maringá", state: "PR", latitude: -23.4205, longitude: -51.9333, timezone: "America/Sao_Paulo" },
  { slug: "mogi-das-cruzes", name: "Mogi das Cruzes", state: "SP", latitude: -23.5229, longitude: -46.1857, timezone: "America/Sao_Paulo" },
  { slug: "piracicaba", name: "Piracicaba", state: "SP", latitude: -22.7343, longitude: -47.6494, timezone: "America/Sao_Paulo" },
  { slug: "bauru", name: "Bauru", state: "SP", latitude: -22.3246, longitude: -49.0871, timezone: "America/Sao_Paulo" },
  { slug: "rio-branco", name: "Rio Branco", state: "AC", latitude: -9.9747, longitude: -67.8100, timezone: "America/Rio_Branco" },
  { slug: "boa-vista", name: "Boa Vista", state: "RR", latitude: 2.8195, longitude: -60.6714, timezone: "America/Manaus" },
  { slug: "palmas", name: "Palmas", state: "TO", latitude: -10.1689, longitude: -48.3317, timezone: "America/Araguaina" },
  { slug: "petropolis", name: "Petrópolis", state: "RJ", latitude: -22.5041, longitude: -43.1785, timezone: "America/Sao_Paulo" },
  { slug: "blumenau", name: "Blumenau", state: "SC", latitude: -26.9194, longitude: -49.0661, timezone: "America/Sao_Paulo" },
  { slug: "jundiai", name: "Jundiaí", state: "SP", latitude: -23.1863, longitude: -46.8844, timezone: "America/Sao_Paulo" },
  { slug: "caruaru", name: "Caruaru", state: "PE", latitude: -8.2824, longitude: -35.9761, timezone: "America/Recife" },
  { slug: "olinda", name: "Olinda", state: "PE", latitude: -8.0089, longitude: -34.8553, timezone: "America/Recife" },
  { slug: "campina-grande", name: "Campina Grande", state: "PB", latitude: -7.2306, longitude: -35.8811, timezone: "America/Fortaleza" },
  { slug: "sao-jose-do-rio-preto", name: "São José do Rio Preto", state: "SP", latitude: -20.8113, longitude: -49.3758, timezone: "America/Sao_Paulo" },
  { slug: "montes-claros", name: "Montes Claros", state: "MG", latitude: -16.7351, longitude: -43.8619, timezone: "America/Sao_Paulo" },
  { slug: "franca", name: "Franca", state: "SP", latitude: -20.5389, longitude: -47.4008, timezone: "America/Sao_Paulo" },
  { slug: "ponta-grossa", name: "Ponta Grossa", state: "PR", latitude: -25.0994, longitude: -50.1583, timezone: "America/Sao_Paulo" },
  { slug: "foz-do-iguacu", name: "Foz do Iguaçu", state: "PR", latitude: -25.5469, longitude: -54.5882, timezone: "America/Sao_Paulo" },
  { slug: "taubate", name: "Taubaté", state: "SP", latitude: -23.0264, longitude: -45.5556, timezone: "America/Sao_Paulo" },
  { slug: "imperatriz", name: "Imperatriz", state: "MA", latitude: -5.5185, longitude: -47.4777, timezone: "America/Fortaleza" },
  { slug: "petrolina", name: "Petrolina", state: "PE", latitude: -9.3891, longitude: -40.5028, timezone: "America/Recife" },
  { slug: "canoas", name: "Canoas", state: "RS", latitude: -29.9175, longitude: -51.1740, timezone: "America/Sao_Paulo" },
  { slug: "volta-redonda", name: "Volta Redonda", state: "RJ", latitude: -22.5023, longitude: -44.1040, timezone: "America/Sao_Paulo" },
  { slug: "santarem", name: "Santarém", state: "PA", latitude: -2.4431, longitude: -54.7081, timezone: "America/Belem" },
  { slug: "cascavel", name: "Cascavel", state: "PR", latitude: -24.9555, longitude: -53.4552, timezone: "America/Sao_Paulo" },
  { slug: "chapeco", name: "Chapecó", state: "SC", latitude: -27.1006, longitude: -52.6158, timezone: "America/Sao_Paulo" },
  { slug: "maraba", name: "Marabá", state: "PA", latitude: -5.3686, longitude: -49.1178, timezone: "America/Belem" },
  { slug: "ilheus", name: "Ilhéus", state: "BA", latitude: -14.7936, longitude: -39.0397, timezone: "America/Bahia" },
  { slug: "uberaba", name: "Uberaba", state: "MG", latitude: -19.7472, longitude: -47.9319, timezone: "America/Sao_Paulo" },
  { slug: "governador-valadares", name: "Governador Valadares", state: "MG", latitude: -18.8511, longitude: -41.9494, timezone: "America/Sao_Paulo" },
  { slug: "sao-carlos", name: "São Carlos", state: "SP", latitude: -22.0174, longitude: -47.8908, timezone: "America/Sao_Paulo" },
  { slug: "limeira", name: "Limeira", state: "SP", latitude: -22.5642, longitude: -47.4017, timezone: "America/Sao_Paulo" },
  { slug: "novo-hamburgo", name: "Novo Hamburgo", state: "RS", latitude: -29.6786, longitude: -51.1300, timezone: "America/Sao_Paulo" },
  { slug: "presidente-prudente", name: "Presidente Prudente", state: "SP", latitude: -22.1207, longitude: -51.3858, timezone: "America/Sao_Paulo" },
  { slug: "divinopolis", name: "Divinópolis", state: "MG", latitude: -20.1388, longitude: -44.8842, timezone: "America/Sao_Paulo" },
  { slug: "santa-maria", name: "Santa Maria", state: "RS", latitude: -29.6842, longitude: -53.8069, timezone: "America/Sao_Paulo" },
  { slug: "arapiraca", name: "Arapiraca", state: "AL", latitude: -9.7525, longitude: -36.6611, timezone: "America/Maceio" },
  { slug: "rondonopolis", name: "Rondonópolis", state: "MT", latitude: -16.4673, longitude: -54.6372, timezone: "America/Cuiaba" },
  { slug: "dourados", name: "Dourados", state: "MS", latitude: -22.2233, longitude: -54.8056, timezone: "America/Campo_Grande" },
  { slug: "criciuma", name: "Criciúma", state: "SC", latitude: -28.6775, longitude: -49.3697, timezone: "America/Sao_Paulo" },
  { slug: "itabuna", name: "Itabuna", state: "BA", latitude: -14.7876, longitude: -39.2781, timezone: "America/Bahia" },
  { slug: "juazeiro-do-norte", name: "Juazeiro do Norte", state: "CE", latitude: -7.2131, longitude: -39.3150, timezone: "America/Fortaleza" },
  { slug: "sobral", name: "Sobral", state: "CE", latitude: -3.6861, longitude: -40.3481, timezone: "America/Fortaleza" },
  { slug: "vitoria-da-conquista", name: "Vitória da Conquista", state: "BA", latitude: -14.8619, longitude: -40.8444, timezone: "America/Bahia" },
  { slug: "parnamirim", name: "Parnamirim", state: "RN", latitude: -5.9156, longitude: -35.2627, timezone: "America/Fortaleza" },
  { slug: "passo-fundo", name: "Passo Fundo", state: "RS", latitude: -28.2628, longitude: -52.4067, timezone: "America/Sao_Paulo" },
  { slug: "pelotas", name: "Pelotas", state: "RS", latitude: -31.7654, longitude: -52.3376, timezone: "America/Sao_Paulo" },
  { slug: "americana", name: "Americana", state: "SP", latitude: -22.7394, longitude: -47.3314, timezone: "America/Sao_Paulo" },
  { slug: "araraquara", name: "Araraquara", state: "SP", latitude: -21.7946, longitude: -48.1754, timezone: "America/Sao_Paulo" },
  { slug: "marilia", name: "Marília", state: "SP", latitude: -22.2139, longitude: -49.9464, timezone: "America/Sao_Paulo" },
];

export function findCityBySlug(slug: string): City | undefined {
  return CITIES.find((c) => c.slug === slug);
}
